/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: f9250317fe9576b82d94a77152ffbdaf)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	DATABASE_URL: string;
	PLUSMARK_HMAC_SECRET: string;
	REACTION_DOCUMENTS: DurableObjectNamespace;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: unknown;
		durableNamespaces: "ReactionDocument";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_URL" | "PLUSMARK_HMAC_SECRET">> {}
}
