/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: c085d2262815e2eb293811d56105346b)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	DATABASE_URL: string;
	REACTION_DOCUMENTS: DurableObjectNamespace;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: unknown;
		durableNamespaces: "ReactionDocument";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_URL">> {}
}
